### ISSUE TITLE
Unexpected crash when creating browser monitor

### ISSUE THREAD

**Issue by MintTeas** [dynatrace-oss/terraform-provider-dynatrace#144]
**Describe the bug**
The plugin crashes when attempting to make a `dynatrace_browser_monitor` with a `keystrokes` event with a `validate` block.

**To Reproduce**
1. Create a script which has a `dynatrace_browser_monitor` with a `keystrokes` event with a `validate` block. (see sample script)
```tf
provider "dynatrace" {
  dt_env_url   = "dt_url"
  dt_api_token = "dt_token"
}
terraform {
  required_providers {
    dynatrace = {
      version = "1.12.1"
      source  = "dynatrace-oss/dynatrace"
    }
  }
}
resource "dynatrace_browser_monitor" "my_test" {
  name      = "demo of bug"
  enabled   = true
  frequency = 15
  locations = ["somewhere"]
  key_performance_metrics {
    load_action_kpm = "VISUALLY_COMPLETE"
    xhr_action_kpm  = "VISUALLY_COMPLETE"
  }
  script {
    type = "clickpath"
    events {
      event {
        description = "Load website"
        navigate {
          url = "www.google.com"
          wait {
            wait_for = "page_complete"
          }
        }
      }
      event {
        description = "Enter text"
        keystrokes {
          text = "123456"
          target {
            locators {
              locator {
                type = "css"
                value = "#somewhere"
              }
            }
          }
          validate {
            validation {
              type = "text_match"
              fail_if_found = true
              match = "something"
              regex = true
            }
          }
        }
      }
    }
  }
}
```
2. run terraform init
3. run terraform apply
4. terraform plugin crashes

**Expected behavior**
Expect either plugin exits with success status or plugin exits with failure status.

**Screenshots**
```
│ Error: Plugin did not respond
│
│   with dynatrace_browser_monitor.my_test,
│   on synthetics.tf line 13, in resource "dynatrace_browser_monitor" "my_test":
│   13: resource "dynatrace_browser_monitor" "my_test" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.

Stack trace from the terraform-provider-dynatrace_v1.12.1.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xb9d5a9]

goroutine 55 [running]:
github.com/dtcookie/dynatrace/api/config/synthetic/monitors/browser.(*WaitCondition).MarshalHCL(0x0, 0x12399da0, 0x10ac567, 0x6)
        github.com/dtcookie/dynatrace/api/config/synthetic/monitors@v1.0.7/browser/wait_condition.go:41 +0x29
github.com/dtcookie/dynatrace/api/config/synthetic/monitors/browser.(*KeyStrokesEvent).MarshalHCL(0x126c89c0, 0x12399d80, 0x10b0b40, 0xb)
        github.com/dtcookie/dynatrace/api/config/synthetic/monitors@v1.0.7/browser/key_strokes_event.go:77 +0x1b9
github.com/dtcookie/dynatrace/api/config/synthetic/monitors/browser.(*EventWrapper).MarshalHCL(0x121679cc, 0x1675390, 0x0, 0x0)
        github.com/dtcookie/dynatrace/api/config/synthetic/monitors@v1.0.7/browser/event.go:84 +0xac
github.com/dtcookie/dynatrace/api/config/synthetic/monitors/browser.Events.MarshalHCL(0x12523670, 0x2, 0x2, 0xd, 0x124d6d40, 0x799361)
        github.com/dtcookie/dynatrace/api/config/synthetic/monitors@v1.0.7/browser/event.go:200 +0x8c
github.com/dtcookie/dynatrace/api/config/synthetic/monitors/browser.(*Script).MarshalHCL(0x12399ba0, 0x12399c00, 0x10bc357, 0x17)
        github.com/dtcookie/dynatrace/api/config/synthetic/monitors@v1.0.7/browser/script.go:55 +0xd4
github.com/dtcookie/dynatrace/api/config/synthetic/monitors.(*BrowserSyntheticMonitorUpdate).MarshalHCL(0x12110f50, 0x122f8020, 0x1f, 0x12110f50)
        github.com/dtcookie/dynatrace/api/config/synthetic/monitors@v1.0.7/browser_synthetic_monitor_update.go:149 +0x1c2
github.com/dynatrace-oss/terraform-provider-dynatrace/resources/synthetic/monitors.reRead(0x11d2a1c, 0x1250a2c0, 0x125fea00, 0xf77b60, 0x124c0300, 0x0, 0x8b3475, 0x12064030)
        github.com/dynatrace-oss/terraform-provider-dynatrace/resources/synthetic/monitors/browser_resource.go:100 +0x223
github.com/dynatrace-oss/terraform-provider-dynatrace/resources/synthetic/monitors.Create(0x11d2a1c, 0x1250a2c0, 0x125fea00, 0xf77b60, 0x124c0300, 0xc0b5c8b4, 0xc49a7e5, 0x0)
        github.com/dynatrace-oss/terraform-provider-dynatrace/resources/synthetic/monitors/browser_resource.go:67 +0x1b8
github.com/dynatrace-oss/terraform-provider-dynatrace/logging.Enable.func1(0x11d2a1c, 0x1250a2c0, 0x125fea00, 0xf77b60, 0x124c0300, 0x1250a2c0, 0x121e3cf8, 0x127000f0)
        github.com/dynatrace-oss/terraform-provider-dynatrace/logging/logging.go:79 +0x63
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x12435810, 0x11d29dc, 0x121a75a0, 0x125fea00, 0xf77b60, 0x124c0300, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.0/helper/schema/resource.go:341 +0x11f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x12435810, 0x11d29dc, 0x121a75a0, 0x121a4620, 0x127000f0, 0xf77b60, 0x124c0300, 0x0, 0x0, 0x0, ...)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.0/helper/schema/resource.go:467 +0x4d9
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x12090190, 0x11d29dc, 0x121a75a0, 0x1208e180, 0x10b6b7c, 0x12, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.0/helper/schema/grpc_provider.go:977 +0x8ce
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x12686140, 0x11d2a3c, 0x121a75a0, 0x121a29c0, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:603 +0x3a1
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x108f560, 0x12686140, 0x11d2a3c, 0x125386d8, 0x126def60, 0x0, 0x11d2a3c, 0x125386d8, 0x1230ce00, 0x64b)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x199
google.golang.org/grpc.(*Server).processUnaryRPC(0x12112120, 0x11d79f4, 0x120a6300, 0x120763f0, 0x12088588, 0x1650c60, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1194 +0x4ea
google.golang.org/grpc.(*Server).handleStream(0x12112120, 0x11d79f4, 0x120a6300, 0x120763f0, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1517 +0xa71
google.golang.org/grpc.(*Server).serveStreams.func1.2(0x12288120, 0x12112120, 0x11d79f4, 0x120a6300, 0x120763f0)
        google.golang.org/grpc@v1.32.0/server.go:859 +0x92
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.32.0/server.go:857 +0x1b0

Error: The terraform-provider-dynatrace_v1.12.1.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: NA
 - Version
   - Terraform v1.2.6
   - terraform-provider-dynatrace: v1.12.1 (reproduced on v1.10.0)

**Additional context**
[validate](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/browser_monitor#nestedblock--script--events--event--tap--validate) is listed as a valid block for [keystrokes](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/browser_monitor#nestedblock--script--events--event--keystrokes) event

**Comment by kishikawa12** [comment]
Hi @MintTeas,

Release 1.13.1 scheduled for this Friday will include a fix for this bug.

Thanks,
Kodai

**Comment by Dynatrace-Reinhard-Pilz** [comment]
[Release v1.13.1](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.13.1) takes care of this issue.
