### ISSUE TITLE
Error while exporting configuration: unsupported elem type managementzones.PropagationType

### ISSUE THREAD

**Issue by gmichels** [dynatrace-oss/terraform-provider-dynatrace#20]
Using 1.0.7 executable to export configuration from one of my tenants:

```
☁  /app  ./terraform-provider-dynatrace download https://<the tenant>.live.dynatrace.com <the key> cfgs
panic: unsupported elem type managementzones.PropagationType

goroutine 1 [running]:
github.com/dtcookie/hcl.(*exportEntries).eval(0xc0004f82e0, 0xd6cf3a, 0x11, 0xc1a8c0, 0xc0003d9500)
        github.com/dtcookie/hcl@v0.0.5/export.go:42 +0x100c
github.com/dtcookie/hcl.(*exportEntries).handle(0xc0004f82e0, 0xc00019f1a0)
        github.com/dtcookie/hcl@v0.0.5/export.go:58 +0xaf
github.com/dtcookie/hcl.(*exportEntries).eval(0xc00018bce8, 0xd63d49, 0x5, 0xc1a8c0, 0xc0003d9700)
        github.com/dtcookie/hcl@v0.0.5/export.go:35 +0x1ae
github.com/dtcookie/hcl.(*exportEntries).handle(0xc00018bce8, 0xc00019f170)
        github.com/dtcookie/hcl@v0.0.5/export.go:58 +0xaf
github.com/dtcookie/hcl.Export(0xe927c0, 0xc0002a6400, 0xe94300, 0xc0004de118, 0x2f, 0x0)
        github.com/dtcookie/hcl@v0.0.5/export.go:69 +0x84
main.importManagementZones(0xc0006a0000, 0x15, 0x7ffe39458cdd, 0x23, 0x7ffe39458d01, 0x60, 0x0, 0x0)
        github.com/dynatrace-oss/terraform-provider-dynatrace/download.go:201 +0x3f0
main.download(0xc0000ca000, 0x5, 0x5, 0xc00009c000)
        github.com/dynatrace-oss/terraform-provider-dynatrace/main.go:108 +0x2b3
main.main()
        github.com/dynatrace-oss/terraform-provider-dynatrace/main.go:151 +0xab
```

Thank you

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello gmichels,

A fix for this issue will be provided with 1.0.8 on Friday.

**Comment by gmichels** [comment]
@Dynatrace-Reinhard-Pilz thanks for the update

**Comment by Dynatrace-Reinhard-Pilz** [comment]
[v1.0.8](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.0.8) takes care of the crashes when downloading Management Zones with Propagation Types specified.
