### ISSUE TITLE
Download of Management Zones is not possible

### ISSUE THREAD

**Issue by ARZ-SagA** [dynatrace-oss/terraform-provider-dynatrace#21]
With Provider Version 1.0.7 download of Management Zones is not possible:

panic: unsupported elem type managementzones.PropagationType

```
goroutine 1 [running]:
github.com/dtcookie/hcl.(*exportEntries).eval(0xc000464020, 0xd6cf3a, 0x11, 0xc1a8c0, 0xc0003f4040)
        github.com/dtcookie/hcl@v0.0.5/export.go:42 +0x100c
github.com/dtcookie/hcl.(*exportEntries).handle(0xc000464020, 0xc0006a4060)
        github.com/dtcookie/hcl@v0.0.5/export.go:58 +0xaf
github.com/dtcookie/hcl.(*exportEntries).eval(0xc000617ce8, 0xd63d49, 0x5, 0xc1a8c0, 0xc0003f4100)
        github.com/dtcookie/hcl@v0.0.5/export.go:35 +0x1ae
github.com/dtcookie/hcl.(*exportEntries).handle(0xc000617ce8, 0xc0006a4030)
        github.com/dtcookie/hcl@v0.0.5/export.go:58 +0xaf
github.com/dtcookie/hcl.Export(0xe927c0, 0xc00016a400, 0xe94300, 0xc00000e008, 0x34, 0x0)
        github.com/dtcookie/hcl@v0.0.5/export.go:69 +0x84
main.importManagementZones(0xc00025d380, 0x1c, 0x7fffdcac2dbc, 0x4b, 0x7fffdcac2e08, 0x60, 0x0, 0x0)
        github.com/dynatrace-oss/terraform-provider-dynatrace/download.go:201 +0x3f0
main.download(0xc0000300a0, 0x5, 0x5, 0xc00007e000)
        github.com/dynatrace-oss/terraform-provider-dynatrace/main.go:108 +0x2b3
main.main()
        github.com/dynatrace-oss/terraform-provider-dynatrace/main.go:151 +0xab
```

**Comment by Dynatrace-Reinhard-Pilz** [comment]
You're right, an unfortunate regression bug. We're pushing out 1.0.8 on Friday, wich will fix this.

**Comment by ARZ-SagA** [comment]
hi,

same error with autotags.PropagationType in the 1.0.8
```
panic: unsupported elem type autotags.PropagationType

goroutine 1 [running]:
github.com/dtcookie/hcl.(*exportEntries).eval(0xc0003062a0, 0xd6d3f3, 0x11, 0xc1f7c0, 0xc0003a4c00)
        github.com/dtcookie/hcl@v0.0.5/export.go:42 +0x100c
github.com/dtcookie/hcl.(*exportEntries).handle(0xc0003062a0, 0xc000296db0)
        github.com/dtcookie/hcl@v0.0.5/export.go:58 +0xaf
github.com/dtcookie/hcl.(*exportEntries).eval(0xc00010dce8, 0xd641cc, 0x5, 0xc1f7c0, 0xc0003a4d00)
        github.com/dtcookie/hcl@v0.0.5/export.go:35 +0x1ae
github.com/dtcookie/hcl.(*exportEntries).handle(0xc00010dce8, 0xc000296d80)
        github.com/dtcookie/hcl@v0.0.5/export.go:58 +0xaf
github.com/dtcookie/hcl.Export(0xe96420, 0xc000514540, 0xe97fe0, 0xc00000e330, 0x29, 0x0)
        github.com/dtcookie/hcl@v0.0.5/export.go:69 +0x84
main.importAutoTags(0xc000310900, 0x14, 0x7fffd04928bc, 0x4b, 0x7fffd0492908, 0x60, 0x0, 0x0)
        github.com/dynatrace-oss/terraform-provider-dynatrace/download.go:271 +0x3ed
main.download(0xc0000300a0, 0x5, 0x5, 0xc00007e000)
        github.com/dynatrace-oss/terraform-provider-dynatrace/main.go:95 +0x1a1
main.main()
        github.com/dynatrace-oss/terraform-provider-dynatrace/main.go:146 +0x78
```

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Thank you for the hint. I've pushed out yet another build today in order to take care of that. Latest Release is now v1.0.9
