### ISSUE TITLE
provider is crashing on dynatrace_request_attribute creation

### ISSUE THREAD

**Issue by ruslanakchurin** [dynatrace-oss/terraform-provider-dynatrace#230]
Hi,

I am trying to create a dynatrace_request_attribute (which I have previously exported from our production environment).
Unlike the majority of other resources which I was able to create, attempts to apply this one lead to rpc error.

```
resource "dynatrace_request_attribute" "processorStatus-imp" {
  name                       = "processorStatus"
  enabled                    = true
  aggregation                = "FIRST"
  confidential               = false
  data_type                  = "STRING"
  normalization              = "ORIGINAL"
  skip_personal_data_masking = false
  data_sources {
    enabled    = true
    source     = "METHOD_PARAM"
    technology = "PHP"
    methods {
      argument_index = 0
      capture        = "ARGUMENT"
      method {
        argument_types    = [ "", "" ]
        class_name        = "ApmEngineDynatrace"
        file_name         = "/data/www/<path>/ApmEngineDynatrace.php"
        file_name_matcher = "EQUALS"
        method_name       = "setAttribute"
        return_type       = ""
        visibility        = "PUBLIC"
      }
    }
    scope {
      service_technology = "PHP_FPM"
    }
    value_processing {
      split_at              = ""
      trim                  = false
      value_extractor_regex = "processorStatus:(.*+)"
      value_condition {
        negate   = false
        operator = "BEGINS_WITH"
        value    = "processorStatus:"
      }
    }
  }
}
```

```
Error: rpc error: code = Unavailable desc = transport is closing

2023-04-12T15:22:43.848Z [DEBUG] plugin.terraform-provider-dynatrace_v1.27.0: 
2023-04-12T15:22:43.848Z [DEBUG] plugin.terraform-provider-dynatrace_v1.27.0: goroutine 30 [running]:
2023-04-12T15:22:43.848Z [DEBUG] plugin.terraform-provider-dynatrace_v1.27.0: github.com/dynatrace-oss/terraform-provider-dynatrace/dynatrace/api/v1/config/requestattributes/settings.(*MethodReference).UnmarshalHCL(0xc0001df900, {0x13edeb0, 0xc000142f00})
2023-04-12T15:22:43.848Z [DEBUG] plugin.terraform-provider-dynatrace_v1.27.0:   github.com/dynatrace-oss/terraform-provider-dynatrace/dynatrace/api/v1/config/requestattributes/settings/method_reference.go:165 +0x9a5
2023-04-12T15:22:43.848Z [DEBUG] plugin.terraform-provider-dynatrace_v1.27.0: github.com/dynatrace-oss/terraform-provider-dynatrace/dynatrace/api/v1/config/requestattributes/settings.(*CapturedMethod).UnmarshalHCL(0xc000a5ed20, {0x13edeb0, 0xc000142ec0})
2023-04-12T15:22:43.848Z [DEBUG] plugin.terraform-provider-dynatrace_v1.27.0:   github.com/dynatrace-oss/terraform-provider-dynatrace/dynatrace/api/v1/config/requestattributes/settings/captured_method.go:126 +0x49f
2023-04-12T15:22:43.848Z [DEBUG] plugin.terraform-provider-dynatrace_v1.27.0: github.com/dynatrace-oss/terraform-provider-dynatrace/dynatrace/api/v1/config/requestattributes/settings.(*DataSource).UnmarshalHCL(0xc0002a2cf0, {0x13edeb0, 0xc000142660})
2023-04-12T15:22:43.848Z [DEBUG] plugin.terraform-provider-dynatrace_v1.27.0:   github.com/dynatrace-oss/terraform-provider-dynatrace/dynatrace/api/v1/config/requestattributes/settings/data_source.go:244 +0xeac
2023-04-12T15:22:43.848Z [DEBUG] plugin.terraform-provider-dynatrace_v1.27.0: github.com/dynatrace-oss/terraform-provider-dynatrace/dynatrace/api/v1/config/requestattributes/settings.(*RequestAttribute).UnmarshalHCL(0xc0001df800, {0x13edf00, 0xc000012a30})
2023-04-12T15:22:43.848Z [DEBUG] plugin.terraform-provider-dynatrace_v1.27.0:   github.com/dynatrace-oss/terraform-provider-dynatrace/dynatrace/api/v1/config/requestattributes/settings/request_attribute.go:170 +0x75d
2023-04-12T15:22:43.848Z [DEBUG] plugin.terraform-provider-dynatrace_v1.27.0: github.com/dynatrace-oss/terraform-provider-dynatrace/terraform/hcl.UnmarshalHCL({0x7f8de03e3a98, 0xc0001df800}, {0x13edf00, 0xc000012a30})
2023-04-12T15:22:43.848Z [DEBUG] plugin.terraform-provider-dynatrace_v1.27.0:   github.com/dynatrace-oss/terraform-provider-dynatrace/terraform/hcl/marshaler.go:45 +0x44
2023-04-12T15:22:43.848Z [DEBUG] plugin.terraform-provider-dynatrace_v1.27.0: github.com/dynatrace-oss/terraform-provider-dynatrace/resources.(*Generic).Create(0xc000092640, {0x13db9b0, 0xc0000898c0}, 0xc0001df680, {0xf068a0, 0xc0000012c0})
2023-04-12T15:22:43.848Z [DEBUG] plugin.terraform-provider-dynatrace_v1.27.0:   github.com/dynatrace-oss/terraform-provider-dynatrace/resources/generic.go:98 +0x170
2023-04-12T15:22:43.848Z [DEBUG] plugin.terraform-provider-dynatrace_v1.27.0: github.com/dynatrace-oss/terraform-provider-dynatrace/provider/logging.Enable.func1({0x13db9b0, 0xc0000898c0}, 0x0?, {0xf068a0, 0xc0000012c0})
2023-04-12T15:22:43.848Z [DEBUG] plugin.terraform-provider-dynatrace_v1.27.0:   github.com/dynatrace-oss/terraform-provider-dynatrace/provider/logging/logging.go:78 +0x83
2023-04-12T15:22:43.849Z [DEBUG] plugin.terraform-provider-dynatrace_v1.27.0: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0004c6000, {0x13db9e8, 0xc000311e90}, 0xd?, {0xf068a0, 0xc0000012c0})
2023-04-12T15:22:43.849Z [DEBUG] plugin.terraform-provider-dynatrace_v1.27.0:   github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:707 +0x12e
2023-04-12T15:22:43.849Z [DEBUG] plugin.terraform-provider-dynatrace_v1.27.0: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0004c6000, {0x13db9e8, 0xc000311e90}, 0xc00066b040, 0xc0000d6f80, {0xf068a0, 0xc0000012c0})
2023-04-12T15:22:43.849Z [DEBUG] plugin.terraform-provider-dynatrace_v1.27.0:   github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:837 +0xa85
2023-04-12T15:22:43.849Z [DEBUG] plugin.terraform-provider-dynatrace_v1.27.0: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00044e1c8, {0x13db9e8?, 0xc000311cb0?}, 0xc0005b8690)
2023-04-12T15:22:43.849Z [DEBUG] plugin.terraform-provider-dynatrace_v1.27.0:   github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/grpc_provider.go:1021 +0xe8d
2023-04-12T15:22:43.849Z [DEBUG] plugin.terraform-provider-dynatrace_v1.27.0: github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000000a00, {0x13db9e8?, 0xc0000b5a10?}, 0xc0002b4070)
2023-04-12T15:22:43.849Z [DEBUG] plugin.terraform-provider-dynatrace_v1.27.0:   github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
2023-04-12T15:22:43.849Z [DEBUG] plugin.terraform-provider-dynatrace_v1.27.0: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1195820?, 0xc000000a00}, {0x13db9e8, 0xc0000b5a10}, 0xc0002b4000, 0x0)
2023-04-12T15:22:43.849Z [DEBUG] plugin.terraform-provider-dynatrace_v1.27.0:   github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
2023-04-12T15:22:43.849Z [DEBUG] plugin.terraform-provider-dynatrace_v1.27.0: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000466000, {0x13f7700, 0xc0006a2000}, 0xc0000e6000, 0xc000311710, 0x1b952e0, 0x0)
2023-04-12T15:22:43.849Z [DEBUG] plugin.terraform-provider-dynatrace_v1.27.0:   google.golang.org/grpc@v1.53.0/server.go:1336 +0xd23
2023-04-12T15:22:43.849Z [DEBUG] plugin.terraform-provider-dynatrace_v1.27.0: google.golang.org/grpc.(*Server).handleStream(0xc000466000, {0x13f7700, 0xc0006a2000}, 0xc0000e6000, 0x0)
2023-04-12T15:22:43.849Z [DEBUG] plugin.terraform-provider-dynatrace_v1.27.0:   google.golang.org/grpc@v1.53.0/server.go:1704 +0xa2f
2023-04-12T15:22:43.849Z [DEBUG] plugin.terraform-provider-dynatrace_v1.27.0: google.golang.org/grpc.(*Server).serveStreams.func1.2()
2023-04-12T15:22:43.849Z [DEBUG] plugin.terraform-provider-dynatrace_v1.27.0:   google.golang.org/grpc@v1.53.0/server.go:965 +0x98
2023-04-12T15:22:43.849Z [DEBUG] plugin.terraform-provider-dynatrace_v1.27.0: created by google.golang.org/grpc.(*Server).serveStreams.func1
2023-04-12T15:22:43.850Z [DEBUG] plugin.terraform-provider-dynatrace_v1.27.0:   google.golang.org/grpc@v1.53.0/server.go:963 +0x28a
2023/04/12 15:22:43 [DEBUG] dynatrace_request_attribute.processorStatus-imp: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2023-04-12T15:22:43.856Z [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2023-04-12T15:22:43.873Z [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/dynatrace-oss/dynatrace/1.27.0/linux_amd64/terraform-provider-dynatrace_v1.27.0 pid=7063 error="exit status 2"
```

Please advise!

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @ruslanakchurin , this issue will be fixed with the upcoming release.
