### ISSUE TITLE
Provider crashes when applying dynatrace_request_naming with a non-existent management zone

### ISSUE THREAD

**Issue by mattBaumBeneva** [dynatrace-oss/terraform-provider-dynatrace#324]
**Describe the bug**
Applying a dynatrace_request_naming resource with a management zone name that does not exist will case the provider to crash with a SEGFAULT in the gRPC plugin.

**To Reproduce**
1. Apply dynatrace_request_naming referencing a MZ name that doesn't exist in Dynatrace
2. Apply crashes and exits with code SEGFAULT

**Expected behavior**
The operation should fail gracefully.

**Additional context**
Here is a sample trace from a Jenkins build:

```
11:54:32  │ Error: Plugin did not respond
11:54:32  │ 
11:54:32  │   with module.main.module.Plan-member-manager-requests.module.request_naming[0].dynatrace_request_naming.rule,
11:54:32  │   on .terraform/modules/main.Plan-member-manager-requests/src/modules/resources/request_naming/main.tf line 11, in resource "dynatrace_request_naming" "rule":
11:54:32  │   11: resource "dynatrace_request_naming" "rule" {
11:54:32  │ 
11:54:32  │ The plugin encountered an error, and failed to respond to the
11:54:32  │ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
11:54:32  │ contain more details.
11:54:32  ╵
11:54:32  
11:54:32  Stack trace from the terraform-provider-dynatrace_v1.40.0 plugin:
11:54:32  
11:54:32  panic: runtime error: invalid memory address or nil pointer dereference
11:54:32  [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xd3905c]
11:54:32  
11:54:32  goroutine 46 [running]:
11:54:32  github.com/dynatrace-oss/terraform-provider-dynatrace/resources.(*Generic).ReadForSettings(0x10c7280?, {0x0?, 0x132ca85?}, 0xc000df9300, {0xffe760?, 0xc00096c620?}, {0x15757e0, 0xc000a6c000})
11:54:32  	github.com/dynatrace-oss/terraform-provider-dynatrace/resources/generic.go:256 +0x25c
11:54:32  github.com/dynatrace-oss/terraform-provider-dynatrace/resources.(*Generic).Read(0xc000129b60, {0x157ee10, 0xc0004eee40}, 0xc000df9300, {0xffe760, 0xc00096c620})
11:54:32  	github.com/dynatrace-oss/terraform-provider-dynatrace/resources/generic.go:321 +0x3fc
11:54:32  github.com/dynatrace-oss/terraform-provider-dynatrace/resources.(*Generic).Create(0xc000129b60, {0x157ee10, 0xc0004eee40}, 0xc000df9300, {0xffe760, 0xc00096c620})
11:54:32  	github.com/dynatrace-oss/terraform-provider-dynatrace/resources/generic.go:208 +0x56f
11:54:32  github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0007f42a0, {0x157ee48, 0xc000cde840}, 0xd?, {0xffe760, 0xc00096c620})
11:54:32  	github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:707 +0x12e
11:54:32  github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0007f42a0, {0x157ee48, 0xc000cde840}, 0xc000a30d00, 0xc000be7180, {0xffe760, 0xc00096c620})
11:54:32  	github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:837 +0xa85
11:54:32  github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00049e288, {0x157ee48?, 0xc000cde720?}, 0xc000a623c0)
11:54:32  	github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/grpc_provider.go:1021 +0xe8d
11:54:32  github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000139720, {0x157ee48?, 0xc000c4fef0?}, 0xc0003577a0)
11:54:32  	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
11:54:32  github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x12ed520?, 0xc000139720}, {0x157ee48, 0xc000c4fef0}, 0xc000357730, 0x0)
11:54:32  	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
11:54:32  google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004b4000, {0x15a1c80, 0xc000324000}, 0xc00100e000, 0xc00086ea20, 0x1e0f9c0, 0x0)
11:54:32  	google.golang.org/grpc@v1.53.0/server.go:1336 +0xd23
11:54:32  google.golang.org/grpc.(*Server).handleStream(0xc0004b4000, {0x15a1c80, 0xc000324000}, 0xc00100e000, 0x0)
11:54:32  	google.golang.org/grpc@v1.53.0/server.go:1704 +0xa2f
11:54:32  google.golang.org/grpc.(*Server).serveStreams.func1.2()
11:54:32  	google.golang.org/grpc@v1.53.0/server.go:965 +0x98
11:54:32  created by google.golang.org/grpc.(*Server).serveStreams.func1
11:54:32  	google.golang.org/grpc@v1.53.0/server.go:963 +0x28a
11:54:32  
11:54:32  Error: The terraform-provider-dynatrace_v1.40.0 plugin crashed!
```

**Comment by mattBaumBeneva** [comment]
We have tested the same pipeline, but creating the MZ first, and the issue does not occur. The cause appears to be the absence of the management zone (refered to by name in the Request Naming rule).

**Comment by kishikawa12** [comment]
Hi @mattBaumBeneva,

Thanks for the feedback and apologies for the inconvenience, the fix will be included in the next release.
