### ISSUE TITLE
Plugin Crash: Importing SLOs

### ISSUE THREAD

**Issue by miguelawili** [dynatrace-oss/terraform-provider-dynatrace#477]
**Describe the bug**
The dynatrace terraform provider plugin crashes when importing SLOs.

**To Reproduce**
1. Create tf skeleton:
```hcl
import {
  to = dynatrace_slo_v2.Base_Apps_EFS_Compliance_API_SLO_Latency_LATENCY
  id = "9ca7696d-8cec-34c5-8e87-a15296471c92"
}

resource "dynatrace_slo_v2" "Base_Apps_EFS_Compliance_API_SLO_Latency_LATENCY" {
  name               = "Base Apps EFS Compliance API SLO Latency LATENCY"
  enabled            = true
  custom_description = "gitlab-project-2568"
  evaluation_type    = "AGGREGATE"
  evaluation_window  = "-4w"
  filter             =<<-EOT
    type("SERVICE"),entityId("SERVICE-86E8F7B067563643")
  EOT
  metric_expression  =<<-EOT
    ((builtin:service.response.time:percentile(95):partition("latency",value("good",lt(500000))):splitBy():count:default(0))/(builtin:service.response.time:percentile(95):splitBy():count)*(100)):default(100,always)
  EOT
  metric_name        = "base_apps_efs_compliance_api_slo_latency_latency"
  target_success     = 99.98
  target_warning     = 99.99000000000001
  error_budget_burn_rate {
    burn_rate_visualization_enabled = true
    fast_burn_threshold             = 10
  }
}

```
2. Run terraform import.
```bash
terraform import dynatrace_slo_v2.Base_Apps_EFS_Compliance_API_SLO_Latency_LATENCY 37589df2-be67-356d-a1ba-5cdb1507d14f
```

**Expected behavior**
I'm able to import my existing SLOs into my Terraform repository.

**Logs**
```
❯ terraform import dynatrace_slo_v2.Base_Apps_EFS_Compliance_API_SLO_Latency_LATENCY 37589df2-be67-356d-a1ba-5cdb1507d14f
dynatrace_slo_v2.Base_Apps_EFS_Compliance_API_SLO_Latency_LATENCY: Importing from ID "37589df2-be67-356d-a1ba-5cdb1507d14f"...
dynatrace_slo_v2.Base_Apps_EFS_Compliance_API_SLO_Latency_LATENCY: Import prepared!
  Prepared dynatrace_slo_v2 for import
dynatrace_slo_v2.Base_Apps_EFS_Compliance_API_SLO_Latency_LATENCY: Refreshing state... [id=37589df2-be67-356d-a1ba-5cdb1507d14f]
╷
│ Error: Request cancelled
│
│ The plugin.(*GRPCProvider).ReadResource request was cancelled.
╵

Stack trace from the terraform-provider-dynatrace_v1.58.5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x104d3c26c]

goroutine 81 [running]:
github.com/dynatrace-oss/terraform-provider-dynatrace/dynatrace/api/builtin/monitoring/slo.(*service).convertToSettings20(0x1400081e6c0?, 0x140002dd400)
	github.com/dynatrace-oss/terraform-provider-dynatrace/dynatrace/api/builtin/monitoring/slo/service.go:246 +0x16c
github.com/dynatrace-oss/terraform-provider-dynatrace/dynatrace/api/builtin/monitoring/slo.(*service).Get(0x1400018e918, {0x1400084e030, 0x24}, 0x14000840630)
	github.com/dynatrace-oss/terraform-provider-dynatrace/dynatrace/api/builtin/monitoring/slo/service.go:152 +0x288
github.com/dynatrace-oss/terraform-provider-dynatrace/dynatrace/api/builtin/monitoring/slo.(*service).GetWithContext(0x14000811bc0?, {0x0?, 0x0?}, {0x1400084e030?, 0x14000870f88?}, 0x1048377e0?)
	github.com/dynatrace-oss/terraform-provider-dynatrace/dynatrace/api/builtin/monitoring/slo/service.go:131 +0x2c
github.com/dynatrace-oss/terraform-provider-dynatrace/dynatrace/settings.(*GenericCRUDService[...]).GetWithContext(0x105a45880?, {0x105a209d8?, 0x14000811bc0?}, {0x1400084e030?, 0x24?}, {0x105a0ecc8?, 0x14000840630?})
	github.com/dynatrace-oss/terraform-provider-dynatrace/dynatrace/settings/generic_crud_service.go:43 +0xc8
github.com/dynatrace-oss/terraform-provider-dynatrace/resources.(*Generic).Read(0x14000612a10, {0x105a20a80, 0x140002cd730}, 0x14000834580, {0x1055e8b60, 0x1400076a460})
	github.com/dynatrace-oss/terraform-provider-dynatrace/resources/generic.go:354 +0x448
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x140006afea0, {0x105a209d8, 0x14000810cc0}, 0x14000834580, {0x1055e8b60, 0x1400076a460})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource.go:795 +0xe4
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0x140006afea0, {0x105a209d8, 0x14000810cc0}, 0x1400084c4e0, {0x1055e8b60, 0x1400076a460})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource.go:1089 +0x408
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x140005c0180, {0x105a209d8?, 0x14000810c00?}, 0x140001c7bc0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/grpc_provider.go:667 +0x3e4
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x140003928c0, {0x105a209d8?, 0x14000810240?}, 0x140001a40c0)
	github.com/hashicorp/terraform-plugin-go@v0.22.0/tfprotov5/tf5server/server.go:775 +0x3c8
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x1059bbb40, 0x140003928c0}, {0x105a209d8, 0x14000810240}, 0x14000834000, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.22.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:482 +0x1c0
google.golang.org/grpc.(*Server).processUnaryRPC(0x1400022f200, {0x105a209d8, 0x140008101b0}, {0x105a38060, 0x1400059da00}, 0x14000818000, 0x140008023c0, 0x1065a58a8, 0x0)
	google.golang.org/grpc@v1.61.1/server.go:1385 +0xb40
google.golang.org/grpc.(*Server).handleStream(0x1400022f200, {0x105a38060, 0x1400059da00}, 0x14000818000)
	google.golang.org/grpc@v1.61.1/server.go:1796 +0xc00
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.61.1/server.go:1029 +0x8c
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 54
	google.golang.org/grpc@v1.61.1/server.go:1040 +0x13c

Error: The terraform-provider-dynatrace_v1.58.5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Desktop (please complete the following information):**
 - OS: macOS. Sonoma 14.5. Apple M1.
 - Terraform v1.8.5
 - Dynatrace Provider Version v1.58.5

**Additional context**
I can provide more details as needed, kindly let me know.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @miguelawili 

When importing the resource `dynatrace_slo_v2` currently doesn't expect an ID like `9ca7696d-8cec-34c5-8e87-a15296471c92`, but the ID under which this SLO is know by the Settings 2.0 API.

You can look up these IDs when executing using this curl command (alternatively via Swagger, ...)

```
curl -X "GET" "https://########.live.dynatrace.com/api/v2/settings/objects?schemaIds=builtin%3Amonitoring.slo&fields=objectId%2Cvalue" -H "accept: application/json; charset=utf-8" -H "Authorization: Api-Token dt0c01.########################.################################################################"  
```

The response should look like this

```
{
  "items": [   
    {
      "objectId": "vu9U3hXa3q0AAAABABZidWlsdGluOm1vbml0b3Jpbmcuc2xvAAZ0ZW5hbnQABnRlbmFudAAkOTYyNTFkOGYtNDZiMi0zMmM2LWJjOTYtNzgzNmVlYjUwODAwvu9U3hXa3q0",
      "value": {
        "enabled": true,
        "name": "Base Apps EFS Compliance API SLO Latency LATENCY",
        "customDescription": "gitlab-project-2568",
...
```

The `objectId` `vu9U3hXa3q0AAAABABZidWlsdGluOm1vbml0b3Jpbmcuc2xvAAZ0ZW5hbnQABnRlbmFudAAkOTYyNTFkOGYtNDZiMi0zMmM2LWJjOTYtNzgzNmVlYjUwODAwvu9U3hXa3q0` is the provider expects you to specify when running `terraform import`.

That's, of course, just a workaround. The provider should accept either kind of ID here - and certainly shouldn't crash.
I've made the necessary changes already - the fix will be included in the upcoming release.
