### ISSUE TITLE
Omitting the `type` attribute for data source `dynatrace_documents` can lead to panic

### ISSUE THREAD

**Issue by Reinhard-Pilz-Dynatrace** [dynatrace-oss/terraform-provider-dynatrace#557]
Using this code snippet against our `sizxxx` tenant
```
data "dynatrace_documents" "all-documents" {

}
```
produces this stack trace.

```
panic: interface conversion: interface {} is nil, not *documents.Document

goroutine 68 [running]:
github.com/dynatrace-oss/terraform-provider-dynatrace/datasources/documents/document.DataSourceRead({0x1dfcb08, 0xc0002be3f0}, 0xc000498b00, {0x17d12e0, 0xc0001e2200})
        C:/Users/Reinhard.Pilz/go/src/github.com/dynatrace-oss/terraform-provider-dynatrace/datasources/documents/document/data_source.go:104 +0x637
github.com/dynatrace-oss/terraform-provider-dynatrace/provider/logging.EnableDSCtx.func1({0x1dfcb08, 0xc0002be3f0}, 0xc000498b00, {0x17d12e0, 0xc0001e2200})
        C:/Users/Reinhard.Pilz/go/src/github.com/dynatrace-oss/terraform-provider-dynatrace/provider/logging/logging.go:134 +0x77
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc00077c460, {0x1dfca60, 0xc00048def0}, 0xc000498b00, {0x17d12e0, 0xc0001e2200})
        C:/Users/Reinhard.Pilz/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource.go:795 +0x119
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc00077c460, {0x1dfca60, 0xc00048def0}, 0xc000498a00, {0x17d12e0, 0xc0001e2200})
        C:/Users/Reinhard.Pilz/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource.go:1015 +0x13a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc000750150, {0x1dfca60?, 0xc00048de30?}, 0xc000496200)
        C:/Users/Reinhard.Pilz/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/grpc_provider.go:1291 +0x34e
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadDataSource(0xc0003be460, {0x1dfca60?, 0xc00048d4d0?}, 0xc000378280)
        C:/Users/Reinhard.Pilz/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.22.0/tfprotov5/tf5server/server.go:686 +0x3f1
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler({0x1b93960, 0xc0003be460}, {0x1dfca60, 0xc00048d4d0}, 0xc000498600, 0x0)
        C:/Users/Reinhard.Pilz/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.22.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:572 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000242e00, {0x1dfca60, 0xc00048d440}, {0x1e142e0, 0xc0002041a0}, 0xc0004b0ea0, 0xc0003c6e70, 0x2a04420, 0x0)
        C:/Users/Reinhard.Pilz/go/pkg/mod/google.golang.org/grpc@v1.61.1/server.go:1385 +0xdd1
google.golang.org/grpc.(*Server).handleStream(0xc000242e00, {0x1e142e0, 0xc0002041a0}, 0xc0004b0ea0)
        C:/Users/Reinhard.Pilz/go/pkg/mod/google.golang.org/grpc@v1.61.1/server.go:1796 +0xfb8
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        C:/Users/Reinhard.Pilz/go/pkg/mod/google.golang.org/grpc@v1.61.1/server.go:1029 +0x7f
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 52
        C:/Users/Reinhard.Pilz/go/pkg/mod/google.golang.org/grpc@v1.61.1/server.go:1040 +0x125
```

The error also happened at customer Schufa, who've mad us aware of it.

**Comment by Reinhard-Pilz-Dynatrace** [comment]
Fixed with the upcoming release
