### ISSUE TITLE
Bug: Dynatrace Provider Crashes When Importing dynatrace_custom_log_source Resource

### ISSUE THREAD

**Issue by nkgovind** [dynatrace-oss/terraform-provider-dynatrace#609]
**Describe the bug**
There appears to be a bug in the Terraform provider for Dynatrace when attempting to import the dynatrace_custom_log_source resource. This issue causes the Dynatrace provider to crash during the import process. The crash disrupts the resource’s state synchronization, potentially leading to incomplete or incorrect state representation in Terraform. This bug affects users relying on the import feature to integrate existing custom log sources into their Terraform-managed infrastructure, requiring a workaround or fix from the provider maintainers.

Resource config 
```
import {
    to = module.dynatrace_log_processing.dynatrace_log_custom_source.test_relay
   id = "sgfsdgfgsfdgdgfdgslmgm.fgsfs"
 }
```
```
Resource "dynatrace_log_custom_source" "test_relay" {
  name    = "strongdm_relay"
  enabled = true
  scope   = "environment"
  custom_log_source {
    type = "LOG_PATH_PATTERN"
    values_and_enrichment {
      custom_log_source_with_enrichment {
        path = "/home/ubuntu/xxx/*.log"
      }
    }
  }
}
```

Error : 
```
Stack trace from the terraform-provider-dynatrace_v1.70.0 plugin:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xb398b2]
goroutine 101 [running]:
github.com/dynatrace-oss/terraform-provider-dynatrace/dynatrace/api/builtin/logmonitoring/customlogsourcesettings.(*service).Get(0xc0007851b0?, {0x183fa00, 0xc00079efc0}, {0xc0006c8160?, 0x126b520?}, 0xc000138b00)
	github.com/dynatrace-oss/terraform-provider-dynatrace/dynatrace/api/builtin/logmonitoring/customlogsourcesettings/service.go:92 +0x92
github.com/dynatrace-oss/terraform-provider-dynatrace/dynatrace/settings.(*GenericCRUDService[...]).Get(...)
	github.com/dynatrace-oss/terraform-provider-dynatrace/dynatrace/settings/generic_crud_service.go:42
github.com/dynatrace-oss/terraform-provider-dynatrace/resources.(*Generic).Read(0xc00037aee0, {0x183faa8, 0xc0003eae00}, 0xc0006c6a80, {0x1208900, 0xc000954100})
	github.com/dynatrace-oss/terraform-provider-dynatrace/resources/generic.go:417 +0x3f1
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0001faa80, {0x183fa00, 0xc000b13800}, 0xc0006c6a80, {0x1208900, 0xc000954100})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource.go:795 +0x119
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0001faa80, {0x183fa00, 0xc000b13800}, 0xc000b17ad0, {0x1208900, 0xc000954100})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource.go:1089 +0x525
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00085a3f0, {0x183fa00?, 0xc000b13740?}, 0xc0001389c0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/grpc_provider.go:667 +0x4aa
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0001200a0, {0x183fa00?, 0xc000b12fc0?}, 0xc000200a20)
	github.com/hashicorp/terraform-plugin-go@v0.22.0/tfprotov5/tf5server/server.go:775 +0x4af
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x15da3e0, 0xc0001200a0}, {0x183fa00, 0xc000b12fc0}, 0xc0006c6800, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.22.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:482 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000300e00, {0x183fa00, 0xc000b12f30}, {0x18575e0, 0xc00024b6c0}, 0xc0006f67e0, 0xc0004fc5d0, 0x2424e28, 0x0)
	google.golang.org/grpc@v1.61.1/server.go:1385 +0xdd1
google.golang.org/grpc.(*Server).handleStream(0xc000300e00, {0x18575e0, 0xc00024b6c0}, 0xc0006f67e0)
	google.golang.org/grpc@v1.61.1/server.go:1796 +0xfb8
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.61.1/server.go:1029 +0x7f
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 16
	google.golang.org/grpc@v1.61.1/server.go:1040 +0x125
Error: The terraform-provider-dynatrace_v1.70.0 plugin crashed!
This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
Cleaning up project directory and file based variables
00:00
ERROR: Job failed: command terminated with exit code 1
```

**Comment by Reinhard-Pilz-Dynatrace** [comment]
Thanks for reporting that bug, @nkgovind 
We are planning to push out a new release by the end of this week. A fix for this issue will be included.
